### ISSUE TITLE
Host API

### ISSUE THREAD

**Issue by MICU-ADMIN** [MICU-ADMIN/Islamic_ware#23]
## Issue: Host API on app.fl0.com with .NET Server and Swagger

**Description:**
We need to host an API on app.fl0.com using a .NET server with a local Swagger instance.

**Task Details:**
- Set up a .NET server.
- Configure the server to run locally.
- Implement Swagger for API documentation.
- Deploy the API on app.fl0.com.

**Steps to Reproduce:**
1. Clone the repository.
2. Install the necessary dependencies.
3. Configure the .NET server.
4. Test locally.
5. Deploy on app.fl0.com.

**Acceptance Criteria:**
- The API should be accessible at app.fl0.com.
- Swagger documentation should be available.
- Successful deployment without errors.

**Additional Information:**
- Provide any additional context or resources related to this task.

https://app.fl0.com/mosqueicu/MosqueICU/dev/api-corporations/deployments

**Comment by hossam1231** [comment]
This has been completed and the backend is live on Fl0

**Comment by hossam1231** [comment]
Marking as closed as this has been completed
